### ISSUE TITLE
Tasks for milestone 1

### ISSUE THREAD

**Issue by nazra-inari** [UBC-MDS/explorePy#2]
- [x] Code of Conduct

- [x] Add contributing.md

- [x] Place holder folders for directory structure (data, src, imgs, docs)

- [x] Create 3 separate .py files. One of for each function with documentation but no code

- [x] Generate black box test cases and test data set to run test cases and comment/document the test cases as well

**Comment by rachelkriggs** [comment]
all items addressed
